# This is a basic workflow to help you get started with Actions

name: DemoNewCD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  deploy_dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'teste.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev
  deploy_hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'teste.com'
    needs: deploy_dev
    steps:
      - name: Run a one-line script
        run: echo Deploy Hml
  deploy_prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'teste.com'
    needs: deploy_hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy prd
